### ISSUE TITLE
Entire bulk download fails if even a single file within fails

### ISSUE THREAD

**Issue by klearned** [BD2KGenomics/dcc-spinnaker-client#20]
Issue: if any single file listed in the manifest fails, none of the files in the manifest can be downloaded...entire bulk download fails and errors out.

To Reproduce:
1. Download manifest from file browser for either of these Centers:THR21 or THR20
2. Use Help page instructions to do a bulk download of either THR21 or THR20
3. Errors out without any files downloaded

Workaround:
Brian wrote a script that runs through a manifest and downloads one at a time. Using that method, there were six files that weren't downloaded, and therefore that we think have issues:

THR20_0508_S01.tar.gz
THR21_0528_S01.tar.gz
THR21_0550_S01.tar.gz
THR21_0551_S01.tar.gz
THR21_0557_S01.tar.gz
THR21_0560_S01.tar.gz

**Comment by klearned** [comment]
@caaespin @wshands 
Was this issue fixed with the new infrastructure? Thanks!

**Comment by klearned** [comment]
I think this was fixed? Should we close this out?

**Comment by wshands** [comment]
Geryl Pelayo @GPelayo  is working on this.

**Comment by kozbo** [comment]
What is the status of this task?
