### ISSUE TITLE
copy icgc client logs to outputs directory

### ISSUE THREAD

**Issue by benjaminran** [BD2KGenomics/dcc-spinnaker-client#33]
Right now `bin/spinnaker-upload` assumes _/outputs_ is used as the output dir and copies the icgc-client logs there after spinnaker.py finishes. If an outputs directory other than _/outputs_ is used, the icgc logs will just be thrown away. To avoid this, spinnaker.py should invoke the icgc clients with environment variable REDWOOD_LOG_DIR=/metadata/output/dir/from/spinnaker/py/invocation

**Comment by kozbo** [comment]
What is the status of this task?
