### ISSUE TITLE
Show upload progress

### ISSUE THREAD

**Issue by benjaminran** [BD2KGenomics/dcc-spinnaker-client#4]
There's a related ticket here:

BD2KGenomics/dcc-storage#21

**Comment by rcurrie** [comment]
Unfortunately all of this appears to happen inside the icgc jar so its opaque. But I think its likely we'll ditch that in the future at which point we can put proper progress in.

**Comment by briandoconnor** [comment]
@caaespin take a look at this ticket when you refresh the client

**Comment by caaespin** [comment]
Upload progress bar now available on the newest release of the core client.
