### ISSUE TITLE
Spinnaker client does not upload files with zero length and reports a failure

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/dcc-spinnaker-client#40]
The Fusion pipeline sometimes produces result files of zero length, which is expected behavior. The spinnaker client fails to upload zero length files and reports an error. This causes the Dockstore Tool Runner to fail the workflow, because it detects an error on uploading result files, whereas the Fusion pipeline has actually succeeded. 

Currently the metadata for the pipeline is uploaded before the result files and indicates that there is a result file when actually there is not. This is a bug that has been reported in the Dockstore Tool Runner.

The Dockstore tool runner should detect the upload failure of a zero length file and not treat it as an error, or there better yet there should be an option for spinnaker client that would allow it to upload a zero length file and indicate success. However we probably want the Spinnaker client to indicate a failure when a user tries to upload a file with zero length using an upload manifest, that is why an extra option for the client that would prevent upload of a zero length file would be good.

**Comment by caaespin** [comment]
@wshands @GPelayo , the spinnaker client acts as a wrapper to the underlying icgc-storage-client (see [here](https://github.com/BD2KGenomics/dcc-storage/tree/develop/icgc-storage-client) and [here](https://github.com/BD2KGenomics/dcc-redwood-client) ). The icgc client is the component that actually restricts the upload of any empty file. Most likely that was their design. Is it possible to have the pipeline just echo the word `empty` to these empty files? This would save you guys the need to dive in and modify the ICGC code.
